---
- name: Check role inputs are valid
  block:
    - name: Check role_nutanix_prism_initial_password_host
      ansible.builtin.fail:
        msg: "the variable 'role_nutanix_prism_initial_password_host' has to be provided."
      when:
        - role_nutanix_prism_initial_password_host is not defined or role_nutanix_prism_initial_password_host == ""

    - name: Check role_nutanix_prism_initial_password_host_password
      ansible.builtin.fail:
        msg: "the variable 'role_nutanix_prism_initial_password_host_password' has to be provided."
      when:
        - role_nutanix_prism_initial_password_host_password is not defined or role_nutanix_prism_initial_password_host_password == ""

    - name: Check role_nutanix_prism_initial_password_new_password
      ansible.builtin.fail:
        msg: "the variable 'role_nutanix_prism_initial_password_new_password' has to be provided."
      when:
        - role_nutanix_prism_initial_password_new_password is not defined or role_nutanix_prism_initial_password_new_password == ""
