---
# tasks file for role_nutanix_prism_initial_password
- name: Check variables
  ansible.builtin.import_tasks: check_variables.yml

- name: Set initial password
  ansible.builtin.import_tasks: initial_password.yml
